# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6274f291c5bbbf80df117ec1d1033813ad70839b931ce3cb544046e3dcc026c003e9e65d03b720fc1b9b7149c6ded6759cfe2090d35af4a016c42036dde78a81

test:
  secret_key_base: 64c2eb7c2165af6e6feb031dabf03119b983bf1d62db8fc993b343aa3ada992e5fc3ecc7c8b5dfba7cf871b5937d05ca28e720f975edec771e511531b9d947fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
